site_name: insta-infra
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Commands:
      - Start: commands/start.md
      - Connect: commands/connect.md
      - Shutdown: commands/shutdown.md
      - List: commands/list.md
  - Customization: customization.md
  - Services: services.md
